[package]
name = "timetrack_jr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
rdev = "0.5.1"
rusqlite = "0.28.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = { version = "1.0.86", features = ["preserve_order"] }
