[package]
name = "timetrack_jr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
json = "0.12.4"
rdev = "0.5.1"
rusqlite = "0.28.0"
